FROM golang:1.21

WORKDIR /app/workspace/back/src/

COPY back/src/go.mod back/src/go.sum ./
RUN go mod download && go mod verify

COPY ./back /app/workspace/back
RUN go build -o /usr/local/bin/app

CMD ["app"]