services:
  agro-back:
    build:
      context: ../
      dockerfile: docker/Dockerfile.back.prod
    image: cr.yandex/crpo99ko4d8e1t7dbt9r/agro-back:$TAG
    ports:
      - "$BACK_PORT:8081"
    env_file: ../.env

  agro-front:
    build:
      context: ../
      dockerfile: docker/Dockerfile.front.prod
    image: cr.yandex/crpo99ko4d8e1t7dbt9r/agro-front:$TAG
    ports:
      - '$FRONT_PORT:5173'
    environment:
      - PORT=5173
      - HOST=0.0.0.0
    env_file: ../.env

  postgres:
    image: postgres:13.3
    ports:
      - "$POSTGRES_PORT:5432"
    env_file: ../.env

volumes:
  resources:
  node_modules_front:
